import { TrendyolProduct, HepsiburadaProduct } from './types';

export const MOCK_TRENDYOL_PRODUCTS: TrendyolProduct[] = [
  {
    id: 't1',
    barcode: '868000000001',
    title: 'Erkek Basic T-Shirt Siyah',
    productMainId: 'MAIN-001',
    stockCode: 'STK-BLK-S',
    brandId: 101,
    brandName: 'Mavi',
    categoryId: 501,
    categoryName: 'Giyim > Tişört',
    quantity: 150,
    listPrice: 299.99,
    salePrice: 249.99,
    vatRate: 10,
    currencyType: 'TRY',
    dimensionalWeight: 1,
    description: '<p>Kaliteli pamuklu kumaş.</p>',
    cargoCompanyId: 10,
    shipmentAddressId: 1234,
    returningAddressId: 1234,
    deliveryOption: { deliveryDuration: 2, fastDeliveryType: 'SAME_DAY' },
    images: [{ url: 'https://picsum.photos/300/400?random=1' }, { url: 'https://picsum.photos/300/400?random=2' }],
    attributes: [{ attributeId: 1, attributeName: 'Beden', attributeValueId: 1, customAttributeValue: 'S' }],
    approved: true,
    archived: false,
    onSale: true,
    rejected: false,
    blacklisted: false,
    batchRequestId: 'REQ-999',
    batchStatus: 'COMPLETED',
    lastModified: Date.now()
  },
  {
    id: 't2',
    barcode: '868000000002',
    title: 'Kadın Deri Çanta Kahverengi',
    productMainId: 'MAIN-002',
    stockCode: 'BAG-BRW-01',
    brandId: 102,
    brandName: 'Pierre Cardin',
    categoryId: 602,
    categoryName: 'Aksesuar > Çanta',
    quantity: 5,
    listPrice: 1200.00,
    salePrice: 999.90,
    vatRate: 20,
    currencyType: 'TRY',
    dimensionalWeight: 3,
    description: 'Hakiki deri.',
    cargoCompanyId: 12,
    shipmentAddressId: 1234,
    returningAddressId: 1234,
    deliveryOption: { deliveryDuration: 3, fastDeliveryType: 'FAST' },
    images: [{ url: 'https://picsum.photos/300/400?random=3' }],
    attributes: [],
    approved: false,
    archived: false,
    onSale: false,
    rejected: true,
    blacklisted: false,
    batchRequestId: 'REQ-1002',
    batchStatus: 'FAILED',
    failureReasons: ['Görsel çözünürlüğü düşük', 'Açıklama yetersiz'],
    lastModified: Date.now() - 86400000
  }
];

export const MOCK_HEPSIBURADA_PRODUCTS: HepsiburadaProduct[] = [
  {
    id: 'h1',
    hepsiburadaSku: 'HBV000001',
    merchantSku: 'STK-BLK-S',
    price: 259.90,
    availableStock: 145,
    dispatchTime: 1,
    cargoCompany1: 'Aras Kargo',
    merchantId: 'M-555',
    categoryId: '1201',
    barcode: '868000000001',
    urunAdi: 'Erkek Basic T-Shirt Siyah',
    urunAciklamasi: 'Pamuklu rahat kesim.',
    marka: 'Mavi',
    garantiSuresi: 24,
    kg: 0.2,
    taxVatRate: 10,
    images: ['https://picsum.photos/300/400?random=1'],
    uploadStatus: 'Success',
    updateDate: Date.now()
  },
  {
    id: 'h2',
    hepsiburadaSku: 'HBV000002',
    merchantSku: 'ELK-KET-01',
    price: 850.00,
    availableStock: 0,
    dispatchTime: 3,
    cargoCompany1: 'Yurtiçi Kargo',
    merchantId: 'M-555',
    categoryId: '3400',
    barcode: '868000000055',
    urunAdi: 'Çelik Su Isıtıcı',
    urunAciklamasi: '1.7 Litre kapasite',
    marka: 'Arzum',
    garantiSuresi: 24,
    kg: 1.5,
    taxVatRate: 20,
    images: ['https://picsum.photos/300/400?random=5', 'https://picsum.photos/300/400?random=6'],
    uploadStatus: 'Error',
    errorMessage: 'Stok yetersiz bilgisi hatalı',
    errorDetails: 'AvailableStock 0 iken satışa açılamaz.',
    updateDate: Date.now() - 100000
  }
];