import type { TrendyolProduct, HepsiburadaProduct } from './types';

export const MOCK_TRENDYOL_PRODUCTS: TrendyolProduct[] = [
  {
    platform: 'trendyol',
    title: 'Apple iPhone 15 Pro Max 256GB Siyah Titanyum',
    barcode: '194253394914',
    productMainId: 'APPLE-IP15PM-256-BLK',
    stockCode: 'IP15PM256B',
    brandId: 'APPLE',
    brandName: 'Apple',
    categoryId: '1',
    categoryName: 'Cep Telefonu',
    quantity: 45,
    salePrice: 54999,
    listPrice: 64999,
    vatRate: 20,
    currencyType: 'TRY',
    dimensionalWeight: 1.2,
    description: 'iPhone 15 Pro Max ile profesyonel fotoğrafçılık deneyimi yaşayın.',
    cargoCompanyId: 'YurticiKargo',
    shipmentAddressId: 'SA-001',
    returningAddressId: 'RA-001',
    deliveryOption: {
      deliveryDuration: 1,
      fastDeliveryType: 'same-day'
    },
    attributes: [
      { attributeId: 'Renk', attributeValueId: 'Siyah Titanyum' },
      { attributeId: 'Hafıza', customAttributeValue: '256GB' }
    ],
    images: [
      { url: 'https://picsum.photos/seed/iphone1/400' },
      { url: 'https://picsum.photos/seed/iphone2/400' }
    ],
    approved: true,
    archived: false,
    onSale: true,
    rejected: false,
    blacklisted: false,
    batchRequestId: 'BR-2025-001',
    batchStatus: 'success',
    failureReasons: [],
    lastUpdated: '2 saat önce'
  },
  {
    platform: 'trendyol',
    title: 'Samsung Galaxy S24 Ultra 512GB Titanium Gray',
    barcode: '8806095259277',
    productMainId: 'SAMSUNG-S24U-512-TG',
    stockCode: 'S24U512TG',
    brandId: 'SAMSUNG',
    brandName: 'Samsung',
    categoryId: '1',
    categoryName: 'Cep Telefonu',
    quantity: 8,
    salePrice: 59999,
    listPrice: 69999,
    vatRate: 20,
    currencyType: 'TRY',
    dimensionalWeight: 1.1,
    description: 'Galaxy S24 Ultra ile yapay zeka destekli fotoğrafçılık.',
    cargoCompanyId: 'Aras',
    shipmentAddressId: 'SA-002',
    returningAddressId: 'RA-002',
    deliveryOption: {
      deliveryDuration: 2,
      fastDeliveryType: 'fast'
    },
    attributes: [
      { attributeId: 'Renk', attributeValueId: 'Titanium Gray' },
      { attributeId: 'Hafıza', customAttributeValue: '512GB' }
    ],
    images: [
      { url: 'https://picsum.photos/seed/samsung1/400' },
      { url: 'https://picsum.photos/seed/samsung2/400' }
    ],
    approved: true,
    archived: false,
    onSale: true,
    rejected: false,
    blacklisted: false,
    batchRequestId: 'BR-2025-002',
    batchStatus: 'success',
    failureReasons: [],
    lastUpdated: '5 saat önce'
  },
  {
    platform: 'trendyol',
    title: 'Sony WH-1000XM5 Kablosuz Gürültü Önleyici Kulaklık',
    barcode: '4548736141392',
    productMainId: 'SONY-WH1000XM5-BLK',
    stockCode: 'SONYWH5B',
    brandId: 'SONY',
    brandName: 'Sony',
    categoryId: '85',
    categoryName: 'Kulaklık',
    quantity: 120,
    salePrice: 12499,
    listPrice: 15999,
    vatRate: 20,
    currencyType: 'TRY',
    dimensionalWeight: 0.5,
    description: 'Endüstri lideri gürültü engelleme teknolojisi.',
    cargoCompanyId: 'MNG',
    shipmentAddressId: 'SA-003',
    returningAddressId: 'RA-003',
    deliveryOption: {
      deliveryDuration: 3,
      fastDeliveryType: 'standard'
    },
    attributes: [
      { attributeId: 'Renk', attributeValueId: 'Siyah' },
      { attributeId: 'Bağlantı', customAttributeValue: 'Bluetooth 5.3' }
    ],
    images: [
      { url: 'https://picsum.photos/seed/sony1/400' }
    ],
    approved: false,
    archived: false,
    onSale: false,
    rejected: false,
    blacklisted: false,
    batchRequestId: 'BR-2025-003',
    batchStatus: 'pending',
    failureReasons: [],
    lastUpdated: '1 gün önce'
  },
  {
    platform: 'trendyol',
    title: 'Dyson V15 Detect Absolute Kablosuz Süpürge',
    barcode: '5025155083147',
    productMainId: 'DYSON-V15-ABS',
    stockCode: 'DYSONV15',
    brandId: 'DYSON',
    brandName: 'Dyson',
    categoryId: '56',
    categoryName: 'Elektrikli Süpürge',
    quantity: 2,
    salePrice: 24999,
    listPrice: 29999,
    vatRate: 20,
    currencyType: 'TRY',
    dimensionalWeight: 3.5,
    description: 'Lazer teknolojisi ile görünmez tozları ortaya çıkarır.',
    cargoCompanyId: 'YurticiKargo',
    shipmentAddressId: 'SA-004',
    returningAddressId: 'RA-004',
    deliveryOption: {
      deliveryDuration: 2,
      fastDeliveryType: 'fast'
    },
    attributes: [
      { attributeId: 'Renk', attributeValueId: 'Gri' },
      { attributeId: 'Güç', customAttributeValue: '230W' }
    ],
    images: [
      { url: 'https://picsum.photos/seed/dyson1/400' },
      { url: 'https://picsum.photos/seed/dyson2/400' }
    ],
    approved: true,
    archived: false,
    onSale: true,
    rejected: false,
    blacklisted: false,
    batchRequestId: 'BR-2025-004',
    batchStatus: 'success',
    failureReasons: [],
    lastUpdated: '4 saat önce'
  }
];

export const MOCK_HEPSIBURADA_PRODUCTS: HepsiburadaProduct[] = [
  {
    platform: 'hepsiburada',
    title: 'MacBook Pro 14" M3 Pro 18GB 512GB Space Black',
    barcode: '195949111310',
    hepsiburadaSku: 'HBV00012345',
    merchantSku: 'APPLE-MBP14-M3P-512-BLK',
    price: 89999,
    availableStock: 5,
    dispatchTime: 1,
    cargoCompany1: 'YurticiKargo',
    cargoCompany2: 'Aras',
    cargoCompany3: '',
    shippingAddressLabel: 'Istanbul Depo',
    shippingProfileName: 'Hizli Gonderim',
    inventoryUploadId: 'IU-2025-100',
    uploadStatus: 'Success',
    errorMessage: '',
    errorDetails: '',
    image: 'https://picsum.photos/seed/macbook1/400',
    lastUpdated: '3 saat önce',
    listingStatus: 'active'
  },
  {
    platform: 'hepsiburada',
    title: 'iPad Pro 12.9" M2 256GB Space Gray Wi-Fi',
    barcode: '194253394815',
    hepsiburadaSku: 'HBV00034567',
    merchantSku: 'APPLE-IPADP-M2-256-SG',
    price: 42999,
    availableStock: 89,
    dispatchTime: 1,
    cargoCompany1: 'MNG',
    cargoCompany2: 'YurticiKargo',
    cargoCompany3: 'Surat',
    shippingAddressLabel: 'Ankara Depo',
    shippingProfileName: 'Standart Gonderim',
    inventoryUploadId: 'IU-2025-101',
    uploadStatus: 'Success',
    errorMessage: '',
    errorDetails: '',
    image: 'https://picsum.photos/seed/ipad1/400',
    lastUpdated: '6 saat önce',
    listingStatus: 'active'
  },
  {
    platform: 'hepsiburada',
    title: 'AirPods Pro 2. Nesil USB-C Şarj Kutusu',
    barcode: '194253850090',
    hepsiburadaSku: 'HBV00056789',
    merchantSku: 'APPLE-APP2-USBC',
    price: 9999,
    availableStock: 150,
    dispatchTime: 2,
    cargoCompany1: 'Aras',
    cargoCompany2: '',
    cargoCompany3: '',
    shippingAddressLabel: 'Izmir Depo',
    shippingProfileName: '',
    inventoryUploadId: 'IU-2025-102',
    uploadStatus: 'Success',
    errorMessage: '',
    errorDetails: '',
    image: 'https://picsum.photos/seed/airpods1/400',
    lastUpdated: '8 saat önce',
    listingStatus: 'active'
  },
  {
    platform: 'hepsiburada',
    title: 'Apple Watch Series 9 GPS 45mm Gece Yarısı Alüminyum Kasa',
    barcode: '195949040146',
    hepsiburadaSku: 'HBV00078901',
    merchantSku: 'APPLE-AW9-45-MID-GPS',
    price: 14999,
    availableStock: 0,
    dispatchTime: 3,
    cargoCompany1: 'YurticiKargo',
    cargoCompany2: 'MNG',
    cargoCompany3: '',
    shippingAddressLabel: 'Istanbul Depo',
    shippingProfileName: 'Hizli Gonderim',
    inventoryUploadId: 'IU-2025-103',
    uploadStatus: 'Error',
    errorMessage: 'Stok yetersiz',
    errorDetails: 'Minimum stok miktarı 1 olmalıdır.',
    image: 'https://picsum.photos/seed/watch1/400',
    lastUpdated: '12 saat önce',
    listingStatus: 'inactive'
  }
];
